services:
  - type: web
    name: affilistore-backend
    env: python
    runtime: python-3.13.1
    region: oregon
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: AMAZON_CREDENTIAL_ID
        sync: false
      - key: AMAZON_CREDENTIAL_SECRET
        sync: false
      - key: AMAZON_PARTNER_TAG
        sync: false
      - key: AMAZON_API_VERSION
        value: "2.2"
      - key: AMAZON_MARKETPLACE
        value: www.amazon.in
      - key: FRONTEND_URL
        sync: false
